# put your secret values and credentials here. do not share this file and do not push it to GitHub
[sources.crypto_data]
# No API key needed for this project

[destination.snowflake.credentials]
database = "dlt_data"
password = "ELparvie@1997"
username = "loader"
host = "chunmln-my_aacount"
warehouse = "COMPUTE_WH"
role = "DLT_LOADER_ROLE"
